/**
 * Task selector — reads an agent's weekly plan and selects tasks to run
 * on the current heartbeat tick.
 *
 * Track-based selection:
 *   - Each task optionally carries a `track` string (e.g. "x-com",
 *     "reddit"). When `track` is absent, `objectiveId` is used as the
 *     default track key so tasks under the same objective pace together.
 *   - At each tick the selector picks ONE top-priority pending task per
 *     distinct track key. Tracks are parallel lanes — the heartbeat
 *     runner drains them serially within a single tick.
 *
 * Ordering:
 *   - Within a track, pick top-priority pending task; ties broken by
 *     original array order (stable).
 *   - Across tracks, the returned array is sorted by the same rule so
 *     the first element is always the overall top-priority task.
 *
 * Daily-review selection (advisor-mode):
 *   - Weekly plans generated by the advisor planner inject five daily-review
 *     tasks (Mon–Fri), all carrying `objectiveId: DAILY_REVIEW_OBJECTIVE_ID`
 *     and `track: DAILY_REVIEW_OBJECTIVE_ID`.  The shared track already
 *     limits selection to ONE daily-review per tick.
 *   - Additionally, when multiple daily-review tasks are simultaneously
 *     eligible (e.g. because the agent was paused and missed a day), only
 *     the most recently scheduled one is kept eligible — the one whose
 *     `runAt` is the largest value ≤ nowMs. This prevents the agent from
 *     doing makeup reflections for past days; it always reflects on the
 *     most current slot available.
 *   - The winning daily-review pick is interleaved with regular task picks
 *     through the normal track-based selection path.
 *
 * Idempotent: pure functions with no side effects; calling
 * selectTasksForTick twice on the same plan returns the same picks.
 *
 * File source of truth: reads from WeeklyPlanStore, never caches.
 */

import {
  DAILY_REVIEW_OBJECTIVE_ID,
} from '../schemas/weekly-plan.schema.js';
import type {
  WeeklyTask,
  WeeklyPlan,
  WeeklyTaskPriority,
  WeeklyPlanStore,
} from '../storage/weekly-plan-store.js';

/** Priority weights — lower number = higher priority */
const PRIORITY_WEIGHT: Record<WeeklyTaskPriority, number> = {
  critical: 0,
  high: 1,
  medium: 2,
  low: 3,
};

/** Default priority when task has none set */
const DEFAULT_PRIORITY: WeeklyTaskPriority = 'medium';

/** Pending-only inbox priority weights for inbox-processor (see below). */
type PriorityKey = WeeklyTaskPriority;

export interface StaleTaskRef {
  taskId: string;
  runAt: string;
  ageMs: number;
}

export interface TaskStatusSummary {
  total: number;
  pending: number;
  completed: number;
  failed: number;
  inProgress: number;
  delegated: number;
  skipped: number;
}

export interface TickPick {
  task: WeeklyTask;
  index: number;
  trackKey: string;
}

export interface SelectTickOptions {
  nowMs?: number;
  maxAgeMs?: number;
}

// ---------------------------------------------------------------------------
// Daily-review recognition
// ---------------------------------------------------------------------------

/**
 * Returns true when the task is a daily-review slot injected by the
 * advisor-mode weekly-plan generator.
 *
 * Use this helper instead of comparing `task.objectiveId` to the raw string
 * so that all callers stay in sync with the single source of truth in the
 * weekly-plan schema.
 *
 * @param {object} [task]
 * @returns {boolean}
 */
export function isDailyReviewTask(task?: Pick<WeeklyTask, 'objectiveId'> | null): boolean {
  return task?.objectiveId === DAILY_REVIEW_OBJECTIVE_ID;
}

/**
 * Among a list of already-eligible tasks, enforce the daily-review
 * once-per-calendar-day rule.
 *
 * Five daily-review tasks exist per week (Mon–Fri), all sharing the track key
 * `DAILY_REVIEW_OBJECTIVE_ID`. When multiple daily-reviews are simultaneously
 * eligible — e.g. because the agent was paused and missed one or more days —
 * only the most recently scheduled one is kept eligible: the review whose
 * `runAt` is the largest UTC timestamp that is still ≤ `nowMs`.
 *
 * Rationale: an advisor-style onboarding guide reflects on the *current* day,
 * not retroactively on missed days. Selecting the most recent slot keeps the
 * daily-review cadence aligned with the actual calendar even when past slots
 * were skipped.
 *
 * Non-daily-review tasks pass through unchanged.
 *
 * @param {object[]} eligibleTasks - Already pending + time-filtered tasks
 * @param {number} nowMs - Current time in milliseconds since epoch
 * @returns {object[]} Tasks with at most one daily-review task included
 */
function applyDailyReviewOncePerDayRule(eligibleTasks: WeeklyTask[], _nowMs: number): WeeklyTask[] {
  const dailyReviews = eligibleTasks.filter(isDailyReviewTask);
  if (dailyReviews.length <= 1) return eligibleTasks; // nothing to deduplicate

  // Pick the daily-review whose runAt is the most recent (largest) that is
  // still ≤ nowMs. Tasks without a valid runAt receive epoch 0 so they lose
  // to any properly-timestamped task (fails-safe: still eligible, just deprioritised).
  let mostRecent: WeeklyTask = dailyReviews[0]!;
  for (const task of dailyReviews) {
    const taskMs = task.runAt ? Date.parse(task.runAt) : 0;
    const bestMs = mostRecent.runAt ? Date.parse(mostRecent.runAt) : 0;
    if (taskMs > bestMs) mostRecent = task;
  }

  // Return all non-daily-review tasks plus the single winning daily-review.
  return [
    ...eligibleTasks.filter((t) => !isDailyReviewTask(t)),
    mostRecent,
  ];
}

/**
 * Get the numeric weight for a priority level.
 * @param {string} [priority] - Priority string
 * @returns {number}
 */
export function priorityWeight(priority?: WeeklyTaskPriority | string | null): number {
  const key = (priority ?? DEFAULT_PRIORITY) as PriorityKey;
  return PRIORITY_WEIGHT[key] ?? PRIORITY_WEIGHT[DEFAULT_PRIORITY];
}

/**
 * Filter tasks to only those that are pending (eligible for execution).
 * @param {object[]} tasks - Array of task objects from a weekly plan
 * @returns {object[]} Pending tasks (new array, no mutation)
 */
export function filterPendingTasks(tasks: WeeklyTask[] | undefined | null): WeeklyTask[] {
  if (!Array.isArray(tasks)) return [];
  return tasks.filter((t) => t.status === 'pending');
}

/**
 * Sort tasks by priority (critical > high > medium > low).
 * Stable sort: tasks with the same priority retain their original order.
 * Returns a new array — does not mutate the input.
 *
 * @param {object[]} tasks - Array of task objects
 * @returns {object[]} Sorted copy
 */
export function sortByPriority(tasks: WeeklyTask[]): WeeklyTask[] {
  // Use index to guarantee stability across engines
  const indexed = tasks.map((t: WeeklyTask, i: number) => ({ task: t, idx: i }));
  indexed.sort((a, b) => {
    const diff = priorityWeight(a.task.priority) - priorityWeight(b.task.priority);
    return diff !== 0 ? diff : a.idx - b.idx;
  });
  return indexed.map((entry) => entry.task);
}

/**
 * Resolve the track key for a task: explicit `track` wins, else
 * `objectiveId` is used so tasks under the same objective share a lane.
 *
 * @param {object} task
 * @returns {string}
 */
export function trackKeyOf(task?: Pick<WeeklyTask, 'track' | 'objectiveId'> | null): string {
  return task?.track ?? task?.objectiveId ?? '__no_track__';
}

/**
 * How far in the past a task's `runAt` can be before the heartbeat
 * stops dispatching it. Tasks whose `runAt` is older than this window
 * are "stale" — the heartbeat runner marks them `skipped` at the top of
 * the tick (see `findStaleTasks` + `runHeartbeatForAgent`) rather than
 * letting them pile up in the FIFO queue and run hours late.
 *
 * The window is fixed at 60 minutes regardless of the user's cron
 * cadence: anything older than an hour is reliably "missed" (laptop was
 * closed, cron was disabled, cat on the keyboard) and the user doesn't
 * want a flurry of catch-up dispatches the next time the heartbeat
 * comes back online.
 */
export const STALE_TASK_WINDOW_MS = 60 * 60 * 1000;

/**
 * Check whether a task's `runAt` slot has arrived AND is still fresh.
 *
 * Missing / malformed `runAt` is treated as always-eligible — we'd
 * rather run a task with a bogus timestamp than block the agent forever
 * on a validator miss. Schema validation already rejects malformed
 * values at write time.
 *
 * A task is ready iff:
 *   - it has no `runAt`, OR
 *   - `runAt <= now` (not scheduled for the future), AND
 *   - `runAt >= now - maxAgeMs` (not stale past the skip window).
 *
 * @param {object} task
 * @param {number} nowMs
 * @param {object} [opts]
 * @param {number} [opts.maxAgeMs=STALE_TASK_WINDOW_MS] - Skip threshold.
 * @returns {boolean}
 */
export function isRunAtReady(
  task: Pick<WeeklyTask, 'runAt'> | null | undefined,
  nowMs: number,
  { maxAgeMs = STALE_TASK_WINDOW_MS }: { maxAgeMs?: number } = {},
): boolean {
  if (!task || task.runAt == null) return true;
  const scheduledMs = Date.parse(task.runAt);
  if (Number.isNaN(scheduledMs)) return true;
  if (scheduledMs > nowMs) return false;
  return scheduledMs >= nowMs - maxAgeMs;
}

/**
 * Return the pending tasks whose `runAt` is older than `now - maxAgeMs`
 * — i.e. the ones `runHeartbeatForAgent` should mark `skipped` at the
 * top of each tick. Tasks without a `runAt`, tasks whose `runAt` is in
 * the future, and tasks that are not `pending` are all left alone.
 *
 * @param {object} plan - A weekly plan object (from WeeklyPlanStore)
 * @param {object} [opts]
 * @param {number} [opts.nowMs=Date.now()]
 * @param {number} [opts.maxAgeMs=STALE_TASK_WINDOW_MS]
 * @returns {Array<{ taskId: string, runAt: string, ageMs: number }>}
 */
export function findStaleTasks(
  plan: WeeklyPlan | null | undefined,
  { nowMs = Date.now(), maxAgeMs = STALE_TASK_WINDOW_MS }: SelectTickOptions = {},
): StaleTaskRef[] {
  if (!plan || !Array.isArray(plan.tasks)) return [];
  const cutoffMs = nowMs - maxAgeMs;
  const stale: StaleTaskRef[] = [];
  for (const task of plan.tasks) {
    if (!task || task.status !== 'pending') continue;
    if (task.runAt == null) continue;
    const scheduledMs = Date.parse(task.runAt);
    if (Number.isNaN(scheduledMs)) continue;
    if (scheduledMs >= cutoffMs) continue;
    stale.push({
      taskId: task.id,
      runAt: task.runAt,
      ageMs: nowMs - scheduledMs,
    });
  }
  return stale;
}

/**
 * Filter tasks that are both pending AND time-eligible (no runAt OR
 * runAt <= now).
 *
 * For daily-review tasks, an additional constraint is applied: when multiple
 * daily-review slots are simultaneously eligible (because past slots were not
 * completed in time), only the most recently scheduled one is retained so the
 * agent reflects on the current day rather than accumulating stale makeup
 * sessions.  See `applyDailyReviewOncePerDayRule` for the full rationale.
 *
 * @param {object[]} tasks
 * @param {object} [opts]
 * @param {number} [opts.nowMs=Date.now()]
 * @returns {object[]}
 */
export function filterEligibleTasks(
  tasks: WeeklyTask[] | undefined | null,
  { nowMs = Date.now(), maxAgeMs }: SelectTickOptions = {},
): WeeklyTask[] {
  const readyOpts = maxAgeMs === undefined ? undefined : { maxAgeMs };
  const pending = filterPendingTasks(tasks).filter((t) => isRunAtReady(t, nowMs, readyOpts));
  return applyDailyReviewOncePerDayRule(pending, nowMs);
}

/**
 * Select one pending task per distinct track from a weekly plan.
 * Returns an array of `{ task, index, trackKey }` sorted by priority
 * (highest first) so callers that only need the top task can take [0].
 *
 * Tasks whose `runAt` is still in the future are excluded; tracks
 * whose only pending tasks are future-scheduled contribute no pick
 * this tick.
 *
 * Returns `[]` if the plan is not approved or has no eligible tasks.
 *
 * @param {object} plan - A weekly plan object (from WeeklyPlanStore)
 * @param {object} [opts]
 * @param {number} [opts.nowMs=Date.now()]
 * @returns {Array<{ task: object, index: number, trackKey: string }>}
 */
export function selectTasksForTickFromPlan(
  plan: WeeklyPlan | null | undefined,
  { nowMs = Date.now(), maxAgeMs }: SelectTickOptions = {},
): TickPick[] {
  if (!plan) return [];
  if (!plan.approved) return [];
  if (!Array.isArray(plan.tasks) || plan.tasks.length === 0) return [];

  const eligibleOpts: SelectTickOptions =
    maxAgeMs === undefined ? { nowMs } : { nowMs, maxAgeMs };
  const eligible = filterEligibleTasks(plan.tasks, eligibleOpts);
  if (eligible.length === 0) return [];

  // Group eligible tasks by track key (explicit `track` or objectiveId).
  const groups = new Map<string, WeeklyTask[]>();
  for (const task of eligible) {
    const key = trackKeyOf(task);
    if (!groups.has(key)) groups.set(key, []);
    groups.get(key)!.push(task);
  }

  // Pick top-priority task per track (stable within priority).
  const picks: TickPick[] = [];
  for (const [trackKey, tasks] of groups) {
    const sorted = sortByPriority(tasks);
    const selected = sorted[0]!;
    const index = plan.tasks.findIndex((t) => t.id === selected.id);
    picks.push({ task: selected, index, trackKey });
  }

  // Order the per-track picks by priority so the first element is the
  // overall top-priority task — preserves backward compatibility for
  // selectNextTaskFromPlan, which just returns picks[0].
  picks.sort((a, b) => {
    const diff = priorityWeight(a.task.priority) - priorityWeight(b.task.priority);
    return diff !== 0 ? diff : a.index - b.index;
  });

  return picks;
}

/**
 * Select the top-priority pending task from a weekly plan.
 * Returns null if the plan is not approved or has no pending tasks.
 *
 * Equivalent to `selectTasksForTickFromPlan(plan)[0]`. Retained for
 * callers that only need a single selection; the heartbeat tick runner
 * uses the multi-pick variant directly.
 *
 * @param {object} plan - A weekly plan object (from WeeklyPlanStore)
 * @returns {{ task: object, index: number } | null}
 */
export function selectNextTaskFromPlan(
  plan: WeeklyPlan | null | undefined,
  opts?: SelectTickOptions,
): { task: WeeklyTask; index: number } | null {
  const picks = selectTasksForTickFromPlan(plan, opts);
  if (picks.length === 0) return null;
  const first = picks[0]!;
  return { task: first.task, index: first.index };
}

/**
 * Get a summary of task statuses from a plan.
 * Useful for heartbeat logging and budget decisions.
 *
 * @param {object} plan - A weekly plan object
 * @returns {{ total: number, pending: number, completed: number, failed: number, inProgress: number, delegated: number, skipped: number }}
 */
export function getTaskStatusSummary(plan: WeeklyPlan | null | undefined): TaskStatusSummary {
  const summary: TaskStatusSummary = {
    total: 0,
    pending: 0,
    completed: 0,
    failed: 0,
    inProgress: 0,
    delegated: 0,
    skipped: 0,
  };

  if (!plan || !Array.isArray(plan.tasks)) return summary;

  summary.total = plan.tasks.length;
  for (const task of plan.tasks) {
    switch (task.status) {
      case 'pending':
        summary.pending++;
        break;
      case 'completed':
        summary.completed++;
        break;
      case 'failed':
        summary.failed++;
        break;
      case 'in-progress':
        summary.inProgress++;
        break;
      case 'delegated':
        summary.delegated++;
        break;
      case 'skipped':
        summary.skipped++;
        break;
    }
  }
  return summary;
}

/**
 * Check if all tasks in a plan are finished (none pending or in-progress).
 * @param {object} plan - A weekly plan object
 * @returns {boolean}
 */
export function isAllTasksFinished(plan: WeeklyPlan | null | undefined): boolean {
  if (!plan || !Array.isArray(plan.tasks) || plan.tasks.length === 0) return true;
  return plan.tasks.every(
    (t: WeeklyTask) => t.status !== 'pending' && t.status !== 'in-progress'
  );
}

/**
 * Select the next pending task for an agent from the store.
 * Loads the latest approved plan and selects the highest-priority pending task.
 *
 * This is the main entry point used by the heartbeat system.
 *
 * @param {import('../storage/weekly-plan-store.js').WeeklyPlanStore} store - Weekly plan store
 * @param {string} agentId - The agent ID
 * @returns {Promise<{ task: object, index: number, week: string, plan: object } | null>}
 */
export async function selectNextTask(
  store: WeeklyPlanStore,
  agentId: string,
): Promise<{ task: WeeklyTask; index: number; week: string; plan: WeeklyPlan } | null> {
  if (!store) throw new Error('store is required');
  if (!agentId) throw new Error('agentId is required');

  const plan = await store.loadLatestApproved(agentId);
  if (!plan) return null;

  const result = selectNextTaskFromPlan(plan);
  if (!result) return null;

  return {
    task: result.task,
    index: result.index,
    week: plan.week,
    plan,
  };
}

/**
 * Load the latest approved plan and select one task per track.
 *
 * Heartbeat's multi-track entry point — the tick runner drains every
 * returned pick serially within a single tick.
 *
 * @param {import('../storage/weekly-plan-store.js').WeeklyPlanStore} store
 * @param {string} agentId
 * @returns {Promise<{
 *   picks: Array<{ task: object, index: number, trackKey: string }>,
 *   week: string | null,
 *   plan: object | null,
 * }>}
 */
export async function selectTasksForTick(
  store: WeeklyPlanStore,
  agentId: string,
): Promise<{ picks: TickPick[]; week: string | null; plan: WeeklyPlan | null }> {
  if (!store) throw new Error('store is required');
  if (!agentId) throw new Error('agentId is required');

  const plan = await store.loadLatestApproved(agentId);
  if (!plan) return { picks: [], week: null, plan: null };

  const picks = selectTasksForTickFromPlan(plan);
  return { picks, week: plan.week, plan };
}

/**
 * Select the next task, considering a specific week rather than latest approved.
 * Useful when the heartbeat knows which week to target.
 *
 * @param {import('../storage/weekly-plan-store.js').WeeklyPlanStore} store
 * @param {string} agentId
 * @param {string} week - YYYY-Www
 * @returns {Promise<{ task: object, index: number, week: string, plan: object } | null>}
 */
export async function selectNextTaskForWeek(
  store: WeeklyPlanStore,
  agentId: string,
  week: string,
): Promise<{ task: WeeklyTask; index: number; week: string; plan: WeeklyPlan } | null> {
  if (!store) throw new Error('store is required');
  if (!agentId) throw new Error('agentId is required');
  if (!week) throw new Error('week is required');

  let plan: WeeklyPlan;
  try {
    plan = await store.load(agentId, week);
  } catch {
    return null; // Plan doesn't exist
  }

  const result = selectNextTaskFromPlan(plan);
  if (!result) return null;

  return {
    task: result.task,
    index: result.index,
    week: plan.week,
    plan,
  };
}
